### ISSUE TITLE
Time to live

### ISSUE THREAD

**Issue by tamsmino** [fstof/flutter_json_store#10]
I am just starting to use this package and I am wondering what the time to live for the elements is?

How many elements can i save in the database?

Best regards.

**Comment by fstof** [comment]
Hi @cahix. Thanks for your interest in this plugin.

The time to live is the time the element will be valid for in the database. For example:

```dart
storage.setItem(key, data, Duration(hours: 5));
```
If you do a `storage.getItem(key);` within 5 hours your data will be returned. If you do this after 5 hours you will not get any data back (`null` is returned) and the data will be deleted to avoid unnecessary database growth.

As for number of elements:

The backing storage SQLite. so any limitations would be based on that. Check out their documentation on this here https://www.sqlite.org/limits.html
You want to take note of `1. Maximum length of a string or BLOB` this will be the limit on the size of the data value you want to store (json string representation)
Each element stored is a single row in the database... so chances are your device will run out of storage before the database reaches its limit :-)

**Comment by tamsmino** [comment]
Thanks!

I just checked what happens if you do not set the time to live and the data will not expire in that case. (If anyone is wondering)
