### ISSUE TITLE
Batched query

### ISSUE THREAD

**Issue by tamsmino** [fstof/flutter_json_store#11]
Is there any way to to a batched query?

I am able to insert a large amount of data (~100000 entries) into the database using the batched saving from the example, but when i try to load all of them at once using " await jsonStore.getListLike('entry-$id');", my app crashes.

**Comment by fstof** [comment]
Hi @cahix.

Unfortunately there is no batch read query. I'm happy to look at any PR's if you are willing to give it a go

**Comment by tamsmino** [comment]
I decided to stick with another database because I also had some other requirements. Thanks for your offer though :)
