### ISSUE TITLE
Clearing on store instance clears all

### ISSUE THREAD

**Issue by Prn-Ice** [fstof/flutter_json_store#2]
I have two instances of `JsonStore` both with different `dbname`'s but still calling `jsonStore.clearDataBase()` on either clears both.
Is there any way to have two independent instances ?

**Comment by Prn-Ice** [comment]
Sorry about that, this issue was born out of my unsuccessful attempt to auto-update the `jsonStore` when new data came in but setting `inMemory = true` and setting a value for the `database` argument seemed to solve this.

**Comment by fstof** [comment]
Hey @Prn-Ice 
1. So `JsonStore` is a singleton. The constructor is actually a factory constructor, so "constructing" multiple instances is all actually the same object.
2. If you supply a `database` object, the `dbName` and `inMemory` won't have any effect. as your supplied database will be the one used and no new instance will be created.

If you think it will help I could look into forcing non-singleton usage by the user.

**Comment by Prn-Ice** [comment]
Thanks, I've been able to resolve my initial issue but I would just like to know, what does the `inMemory` parameter do?

**Comment by fstof** [comment]
By default all data is persisted on device storage. The `inMemory` option is used if you don't need persistent storage, any data will only be kept in memory, when the app is terminated, the data is also lost
