### ISSUE TITLE
Desktop Support

### ISSUE THREAD

**Issue by Luckey-Elijah** [fstof/flutter_json_store#3]
Hello! I enjoy the plugin. I have used it on several mobile app projects.

Does this plugin also work for Desktop Flutter applications?

Thank you!

**Comment by fstof** [comment]
Hi @Luckey-Elijah 
I have not spent any time on Flutter Desktop yet. I really need to get to it asap.

Have a look at the dependencies. I suspect if they all support Desktop I don't see why this one won't.

**Comment by fstof** [comment]
Once the dependencies support desktop we can relook this.

Closing until then

Thanks
