### ISSUE TITLE
Is there a way to delete many entries at once?

### ISSUE THREAD

**Issue by mcavazotti** [fstof/flutter_json_store#6]
It would be nice to have a method similar to `getListLike` that deletes entries, something like `deleteListLike`.

I'm new to Dart, but I think the implementation of this method would go along these lines:
``` dart
Future<void> deleteListLike(String key,) async {
    await db.delete(
         _table,
         where: 'key = ?',
         whereArgs: [key],
    );
}
```

**Comment by fstof** [comment]
Good idea... Will look into this.

might probably be called just `deleteLike`

**Comment by fstof** [comment]
check out v1.1.0 

Enjoy
