### ISSUE TITLE
Way to specify database path

### ISSUE THREAD

**Issue by doc-rj-celltrak** [fstof/flutter_json_store#7]
Thanks for this package, it looks good. This is not an issue but an enhancement idea. It would be nice to be able to specify the database path. The iOS documents directory will get backed up to iCloud, and there's no good way to prevent it. We need to use a different path to exclude it from getting backed up.

And, one more idea. It would be nice to have a way to disable timeToLive completely. We need a key/value pair to last for the lifetime of the app, but with the current API we would have to use something like timeToLive: const Duration(days: maxInteger), where maxInteger is 1<<63. Is there any alternative? It would be nice to be able to disable the TTL feature.

Thanks again!

**Comment by fstof** [comment]
Thanks for the suggestion. 

I might just look at it. just a little backed up with work. But PR's are always welcome.

**Comment by fstof** [comment]
Hi @doc-rj-celltrak 
Please have a look at v1.2.0 see if that works for you.

Thank you

**Comment by doc-rj-celltrak** [comment]
Looks good thanks for your support.
