### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by vincent-76** [fstof/flutter_json_store#9]
Please migrate this plugin to null safety. Thank you.

**Comment by fstof** [comment]
Thanks @Vincent-76 

This is definitely on my todo list. So thank you for logging.

I just need to sort out v1.4.0 which is currently under testing

**Comment by hanyska** [comment]
+1

**Comment by fstof** [comment]
Hi @Vincent-76 

I have a null safety version out.

Please have a look at https://pub.dev/packages/json_store/versions/2.0.0-nullsafety.0 and let me know if all is good

Thanks

**Comment by stephane-couget** [comment]
Hi @fstof 
I have been testing your plugin in null safety version for two good months on a pro app and I am pleased to inform you that for the moment I have not detected any problem of use. However, I am not yet using the secure part.

I took the time to look at your code and I am very impressed with the content. You did a great job. Well done.

Thanks
